

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvcoop-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env   # ✅ Mount your .env file
    networks:
      - mvcoop-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mvcoop-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: food_order
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - mvcoop-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mvcoop-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - mvcoop-network

volumes:
  db_data:

networks:
  mvcoop-network: